# Site settings
title: Vasile Ungureanu
description: "Personal blog"
url: "https://vasileungureanu.com"

# Author
author:
  name: Vasile Ungureanu
  url: https://vasileungureanu.github.io/about
  email: vasile.v.ungureanu@gmail.com

# Integrations  
disqus_identifier: vasileungureanu
google_analytics: UA-147818401-1

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 15

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
